[project]
name = "hybrid-naive-bayes"
version = "0.1.0"
description = "Hybrid Naive Bayes implementation"
requires-python = ">=3.11"
dependencies = ["requests"]

[project.optional-dependencies]
dev = ["ruff", "pyright", "pytest", "pytest-cov", "coverage[toml]", "pre-commit"]

[tool.pyright]
pythonVersion = "3.11"
typeCheckingMode = "basic"
extraPaths = ["src"]

[tool.pytest.ini_options]
addopts = "--cov=src --cov-report=term-missing"
