name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v1
        with:
          python-version: "3.11"
      - run: uv sync --dev
      - run: uv run pre-commit run --show-diff-on-failure --color always --all-files
